use_frameworks!

platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'FMDBMigrationManager_Example' do
  pod 'FMDBMigrationManager', :path => '../'

  target 'FMDBMigrationManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
